<a href="https://colab.research.google.com/github/diksha-more/task-1/blob/main/Copy_of_Main1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data=pd.read_csv("Employee.csv")

In [ ]:
data

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
df.describe()

,JoiningYear,PaymentTier,Age,ExperienceInCurrentDomain,LeaveOrNot
count,4653.000000,4653.000000,4653.000000,4653.000000,4653.000000
mean,2015.062970,2.698259,29.393295,2.905652,0.343864
std,1.863377,0.561435,4.826087,1.558240,0.475047
min,2012.000000,1.000000,22.000000,0.000000,0.000000
25%,2013.000000,3.000000,26.000000,2.000000,0.000000
50%,2015.000000,3.000000,28.000000,3.000000,0.000000
75%,2017.000000,3.000000,32.000000,4.000000,1.000000
max,2018.000000,3.000000,41.000000,7.000000,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

In [ ]:
df.isnull()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
4648,False,False,False,False,False,False,False,False,False
4649,False,False,False,False,False,False,False,False,False
4650,False,False,False,False,False,False,False,False,False
4651,False,False,False,False,False,False,False,False,False
4652,False,False,False,False,False,False,False,False,False

In [ ]:
df.notnull()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
4648,True,True,True,True,True,True,True,True,True
4649,True,True,True,True,True,True,True,True,True
4650,True,True,True,True,True,True,True,True,True
4651,True,True,True,True,True,True,True,True,True
4652,True,True,True,True,True,True,True,True,True

In [ ]:
df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [ ]:
df.tail()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
df.head(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0
9,Masters,2017,New Delhi,2,37,Male,No,2,0

In [ ]:
df.tail(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
df.shape[0]

4653

In [ ]:
df.shape[1]

9

In [ ]:
print(df.shape)

(4653, 9)

In [ ]:
print(df.dtypes)

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object

In [ ]:
df.dtypes

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object

In [ ]:
df['Education']=df['Education'].astype(bool)

In [ ]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,True,2017,Bangalore,3,34,Male,No,0,0
1,True,2013,Pune,1,28,Female,No,3,1
2,True,2014,New Delhi,3,38,Female,No,2,0
3,True,2016,Bangalore,3,27,Male,No,5,1
4,True,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,True,2013,Bangalore,3,26,Female,No,4,0
4649,True,2013,Pune,2,37,Male,No,2,1
4650,True,2018,New Delhi,3,27,Male,No,5,1
4651,True,2012,Bangalore,3,30,Male,Yes,2,0
4652,True,2015,Bangalore,3,33,Male,Yes,4,0

In [ ]:
df['Age']=df['Age'].astype(float)

In [ ]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,True,2017,Bangalore,3,34.0,Male,No,0,0
1,True,2013,Pune,1,28.0,Female,No,3,1
2,True,2014,New Delhi,3,38.0,Female,No,2,0
3,True,2016,Bangalore,3,27.0,Male,No,5,1
4,True,2017,Pune,3,24.0,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,True,2013,Bangalore,3,26.0,Female,No,4,0
4649,True,2013,Pune,2,37.0,Male,No,2,1
4650,True,2018,New Delhi,3,27.0,Male,No,5,1
4651,True,2012,Bangalore,3,30.0,Male,Yes,2,0
4652,True,2015,Bangalore,3,33.0,Male,Yes,4,0

In [ ]:
scaler=MinMaxScaler()

In [ ]:
df['Join_Scaled']=scaler.fit_transform(df[['JoiningYear']])

In [ ]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Join_Scaled
0,True,2017,Bangalore,3,34.0,Male,No,0,0,0.833333
1,True,2013,Pune,1,28.0,Female,No,3,1,0.166667
2,True,2014,New Delhi,3,38.0,Female,No,2,0,0.333333
3,True,2016,Bangalore,3,27.0,Male,No,5,1,0.666667
4,True,2017,Pune,3,24.0,Male,Yes,2,1,0.833333
...,...,...,...,...,...,...,...,...,...,...
4648,True,2013,Bangalore,3,26.0,Female,No,4,0,0.166667
4649,True,2013,Pune,2,37.0,Male,No,2,1,0.166667
4650,True,2018,New Delhi,3,27.0,Male,No,5,1,1.000000
4651,True,2012,Bangalore,3,30.0,Male,Yes,2,0,0.000000
4652,True,2015,Bangalore,3,33.0,Male,Yes,4,0,0.500000

In [ ]:
scaler=StandardScaler()

In [ ]:
df['Join_Scaled']=scaler.fit_transform(df[['JoiningYear']])

In [ ]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Join_Scaled
0,True,2017,Bangalore,3,34.0,Male,No,0,0,1.039638
1,True,2013,Pune,1,28.0,Female,No,3,1,-1.107233
2,True,2014,New Delhi,3,38.0,Female,No,2,0,-0.570515
3,True,2016,Bangalore,3,27.0,Male,No,5,1,0.502921
4,True,2017,Pune,3,24.0,Male,Yes,2,1,1.039638
...,...,...,...,...,...,...,...,...,...,...
4648,True,2013,Bangalore,3,26.0,Female,No,4,0,-1.107233
4649,True,2013,Pune,2,37.0,Male,No,2,1,-1.107233
4650,True,2018,New Delhi,3,27.0,Male,No,5,1,1.576356
4651,True,2012,Bangalore,3,30.0,Male,Yes,2,0,-1.643951
4652,True,2015,Bangalore,3,33.0,Male,Yes,4,0,-0.033797

In [ ]:
encoder=LabelEncoder()

In [ ]:
df['Age_encoded']=encoder.fit_transform(df['Age'])

In [ ]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot,Join_Scaled,Age_encoded
0,True,2017,Bangalore,3,34.0,Male,No,0,0,1.039638,12
1,True,2013,Pune,1,28.0,Female,No,3,1,-1.107233,6
2,True,2014,New Delhi,3,38.0,Female,No,2,0,-0.570515,16
3,True,2016,Bangalore,3,27.0,Male,No,5,1,0.502921,5
4,True,2017,Pune,3,24.0,Male,Yes,2,1,1.039638,2
...,...,...,...,...,...,...,...,...,...,...,...
4648,True,2013,Bangalore,3,26.0,Female,No,4,0,-1.107233,4
4649,True,2013,Pune,2,37.0,Male,No,2,1,-1.107233,15
4650,True,2018,New Delhi,3,27.0,Male,No,5,1,1.576356,5
4651,True,2012,Bangalore,3,30.0,Male,Yes,2,0,-1.643951,8
4652,True,2015,Bangalore,3,33.0,Male,Yes,4,0,-0.033797,11